### PR TITLE
go.mod: gvisor.dev/gvisor v0.0.0-20230518002134-99c295d3b367

### PR DESCRIPTION
**Pull request by AkihiroSuda**
https://github.com/google/gvisor/compare/a78e892a26d2...99c295d3b367

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@baude @cfergeau PTAL, and also please consider merging other dependency PRs 🙏 (https://github.com/containers/gvisor-tap-vsock/pulls)

**Comment by AkihiroSuda** [comment]
Looks like to need Go 1.20
```
GOARCH=amd64 GOOS=windows go build -ldflags '-s -w' -o bin/gvproxy-windows.exe ./cmd/gvproxy
# gvisor.dev/gvisor/pkg/tcpip
Error: vendor/gvisor.dev/gvisor/pkg/tcpip/tcpip.go:224:23: cannot convert a.addr[:4] (value of type []byte) to type [4]byte
Error: vendor/gvisor.dev/gvisor/pkg/tcpip/tcpip.go:232:24: cannot convert a.addr[:1[6](https://github.com/containers/gvisor-tap-vsock/actions/runs/5009215934/jobs/8977917168?pr=219#step:4:7)] (value of type []byte) to type [16]byte
note: module requires Go 1.20
make: *** [Makefile:53: cross] Error 2
```

**Comment by cfergeau** [comment]
At this point, I'm reluctant to require go 1.20, as I still need to build gvisor-tap-vsock with older golang versions (1.19 is fine). I'll hold this PR for a little while until I make a 0.6.2 release with the other pending PRs, and we can merge this with the 1.20 requirement and work towards a 0.7.0 release. 
If you need a more up to date gvisor fork, I've tested that `gvisor.dev/gvisor@b7014294633b8e28c36a57e729bd0f582143f404` works with 1.19.

**Comment by AkihiroSuda** [comment]
> If you need a more up to date gvisor fork, I've tested that gvisor.dev/gvisor@b7014294633b8e28c36a57e729bd0f582143f404 works with 1.19.

Thanks, but looks like this version can't be compiled with Go 1.20
```console
$ make
go build -ldflags '-s -w' -o bin/gvproxy ./cmd/gvproxy
# gvisor.dev/gvisor/pkg/gohacks
vendor/gvisor.dev/gvisor/pkg/gohacks/string_go120_unsafe.go:27:7: unsafe.StringData requires go1.20 or later (-lang was set to go1.18; check go.mod)
vendor/gvisor.dev/gvisor/pkg/gohacks/string_go120_unsafe.go:38:9: unsafe.String requires go1.20 or later (-lang was set to go1.18; check go.mod)
make: *** [Makefile:14: gvproxy] Error 1
```

**Comment by cfergeau** [comment]
> Thanks, but looks like this version can't be compiled with Go 1.20

Ah indeed, I forgot to check that :-/ Do you require some fixes/features from newer gvisor code? Or was it "only" to keep it up to date?

**Comment by AkihiroSuda** [comment]
> > Thanks, but looks like this version can't be compiled with Go 1.20
> 
> Ah indeed, I forgot to check that :-/ Do you require some fixes/features from newer gvisor code? Or was it "only" to keep it up to date?

Just for keeping it up to date

**Comment by cfergeau** [comment]
One thing I did not realize is that current git main is not compiling with go 1.20

**Pull request closed without merging**
