### PR TITLE
ssh: Recreate connection on retries in setupProxy

### PR DESCRIPTION
**Pull request by cfergeau**
The previous fix was not working as expected, as the ssh go code will
close the underlying connection when there's a failure.
This was causing the retries for CreateBastion() to fail, as after the
first failure it would try to use a closed connection.

This commit recreates the connection each time before calling
CreateBastion() to fix this. This also simplifies the code.

### CODE REVIEW

**Review by jakecorrenti — APPROVED** [review]
LGTM

**Comment by cfergeau** [comment]
The CI failure seems related to `time="2024-01-15T15:06:07Z" level=info msg="Detected Kernel panic, retrying..."` which is very unexpected. This test passed today in other PRs https://github.com/containers/gvisor-tap-vsock/actions/runs/7524944350/job/20490954791
I don't see how this PR could trigger a panic in the guest kernel, wondering if this could be a bug in the gh actions image, as the failing test uses a macos-12 with version: 20240105.1 while the working one uses 20240105.3

**Comment by baude** [comment]
code LGTM

**Comment by baude** [comment]
i re-ran the tests, assume it is a flake ... dealer's choice

/hold
/lgtm

**Comment by cfergeau** [comment]
Yeah, also ran the tests on a macos13 x86_64 machine, and I could not reproduce the issue.

**Comment by cfergeau** [comment]
Since this PR has the 'hold' label, I'll revert the changes for a try, and see if CI behaves better.

**Comment by cfergeau** [comment]
Ok, even git master is currently failing, even if it was green yesterday. Let's ignore the red CI for now, I'll take a closer look with a dummy "debug CI" PR

**Comment by cfergeau** [comment]
And with one more try it's green, go figure!

**Comment by cfergeau** [comment]
Trying to readd /lgtm, but not sure I'm allowed to
/lgtm

**Pull request merged**
