### PR TITLE
Update gvisor to latest tagged release

### PR DESCRIPTION
**Pull request by cfergeau**

### CODE REVIEW

**Comment by praveenkumar** [comment]
No sure if it is expected or rpm build failure is something to do with this PR
```
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 178b6a15b2204cdcb784434158b3abe3 -D /var/lib/mock/fedora-39-aarch64-1726659942.796897/root -a -u mockbuild --capability=cap_ipc_lock --rlimit=RLIMIT_NOFILE=10240 --capability=cap_ipc_lock --bind=/tmp/mock-resolv.u32vskfm:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin '--setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007"' '--setenv=PS1=<mock-chroot> \s-\v\$ ' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c '/usr/bin/rpmbuild -bb  --target aarch64 --nodeps /builddir/build/originals/gvisor-tap-vsock.spec'

Copr build error: Build failed
```

**Comment by cfergeau** [comment]
> Edit: so f39 issue is #400 one.

I've updated #400 to also update the go versions used in github actions as we no longer support 1.21.

**Comment by cfergeau** [comment]
> No sure if it is expected or rpm build failure is something to do with this PR
> 
> ```
> ERROR: Command failed: 
>  # /usr/bin/systemd-nspawn -q -M 178b6a15b2204cdcb784434158b3abe3 -D /var/lib/mock/fedora-39-aarch64-1726659942.796897/root -a -u mockbuild --capability=cap_ipc_lock --rlimit=RLIMIT_NOFILE=10240 --capability=cap_ipc_lock --bind=/tmp/mock-resolv.u32vskfm:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin '--setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007"' '--setenv=PS1=<mock-chroot> \s-\v\$ ' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c '/usr/bin/rpmbuild -bb  --target aarch64 --nodeps /builddir/build/originals/gvisor-tap-vsock.spec'
> 
> Copr build error: Build failed
> ```
> 
> Edit: so f39 issue is #400 one.

I've rebased the PR now that #400 has been merged.

**Pull request merged**
