### PR TITLE
Ignore ErrUnexpectedEOF in panicCheck and fix lint issue

### PR DESCRIPTION
**Pull request by balajiv113**
This PR does the following,
1. Fixes the flaky test as discussed in https://github.com/containers/gvisor-tap-vsock/pull/135
2. Fixes the lint issues due to the use of deprecated package io/ioutils

### CODE REVIEW

**Comment by balajiv113** [comment]
@gbraad 
I believe this PR should fix the flaky test failures and current lint failures as well. 
This should bring the CI runs back to green

**Comment by n1hility** [comment]
lgtm

**Comment by cfergeau** [comment]
Rebased on top of main, there's only one commit left: https://github.com/cfergeau/gvisor-tap-vsock/commit/3b4e56442bbea0f66f6bf129bc540ebcc0d732bb

**Comment by balajiv113** [comment]
@cfergeau sure will look into it and update

**Comment by balajiv113** [comment]
@cfergeau  Done the changes.

**Review by cfergeau — APPROVED** [review]

**Pull request merged**
