### PR TITLE
Packit: switch to rpm/gvisor-tap-vsock.spec

### PR DESCRIPTION
**Pull request by lsm5**
gvisor-tap-vsock has now been included as a separate Fedora package.
    
This commit also enables downstream Fedora packaging tasks on upstream
release.

### CODE REVIEW

**Comment by lsm5** [comment]
`rpm-build:fedora-rawhide-*` is going to fail until upstream is fixed to build with go1.21. Those task failures are best ignored for now.

**Comment by cfergeau** [comment]
Is this PR still needed? I've rebased it in https://github.com/cfergeau/gvisor-tap-vsock/tree/packit-update

**Comment by lsm5** [comment]
I need to rebase this on main.

**Comment by cfergeau** [comment]
> I need to rebase this on main.

@lsm5 I've already done this in https://github.com/cfergeau/gvisor-tap-vsock/tree/packit-update

**Comment by lsm5** [comment]
conditionalized go-rpm-macros. The c9s failure are a result of a faulty `%{golang_arches_future}` which I'm checking on with the toolset team. We can ignore c9s for now.

**Comment by lsm5** [comment]
@cfergeau PTAL

**Comment by lsm5** [comment]
@cfergeau once this is merged, whenever there's a new release published to github, packit will create rpm update PRs to https://src.fedoraproject.org/rpms/gvisor-tap-vsock , which will need a human to review and merge. After packit's first PR, subsequent PRs should have a minimal diff.

**Comment by lsm5** [comment]
This needs a small change for correct obsoletion. Updating..

**Comment by lsm5** [comment]
> This needs a small change for correct obsoletion. Updating..

Done.

**Comment by baude** [comment]
LGTM

**Comment by lsm5** [comment]
@cfergeau this is good to go. PTAL.

**Review by baude — APPROVED** [review]

**Pull request merged**
